services:
  dashboard:
    container_name: dashboard-ford
    image: dashboard-ford:latest
    ports:
      - "8050:8050"
    environment:
      - DB_SERVER=host.docker.internal
      - DB_PORT=1433
      - DB_DATABASE=W_Access
      - DB_USERNAME=sa
      - DB_PASSWORD=#w_access_Adm#
      - DASH_DEBUG=false
      - DASH_HOST=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
