# setup/docker-compose.yml
version: '3'

services:
  dashboard:
    container_name: dashboard-ford
    build:
      context: ..  # Aponta para a pasta raiz do projeto
      dockerfile: setup/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ../data:/app/data
      - ../exports:/app/exports
      - ../aux_files:/app/aux_files
      - ../config:/app/config
    environment:
      - DB_SERVER=host.docker.internal  # Para acessar o SQL Server no host
      - DB_PORT=1433
      - DB_DATABASE=W_Access
      - DB_USERNAME=sa
      - DB_PASSWORD=#w_access_Adm#
      - DASH_DEBUG=false
      - DASH_HOST=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"